
#INCLUDE <p16f877.inc>

ORG 0 
GOTO INICIO 
ORG 5 

INICIO: 	
			MOVLW	0X20			;W <- 0X20
			MOVWF	FSR				;FSR <- 0X20
			MOVF	INDF,W			;W <- INDF
			MOVWF	0X40			;W -> 40H
SIGUIENTE:	INCF	FSR,1			;FSR++
			MOVF	INDF,W			;W <- INDF
			SUBWF	0X40,W			;W <- (40H) - (INDF)
			BTFSS	STATUS,C		;40H < INDF?
			GOTO	CONTINUA		;NO
INTERCAMBIA:						;SI
			MOVF 	INDF,W			;W <- INDF
			MOVWF	0X40			;W -> 40H
CONTINUA:
			MOVF	FSR,W			;W <- FSR
			SUBLW	40H				;W <- 40H - W
			BTFSS	STATUS,Z		;FSR = 40H?
			GOTO 	SIGUIENTE		;NO
			SLEEP					;Si
END